language: php

before_script:
    - composer install --dev --prefer-source

script: vendor/bin/phpunit  --verbose

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

notifications:
  email:
    - rudy@onfroy.net